name: riden_power_supply
description: RIDEN Digital Programmable Power Supply - PC Upper Monitor
publish_to: 'none'
version: 1.0.3+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  fl_chart: ^0.70.2
  provider: ^6.1.2
  flutter_libserialport: ^0.4.0
  window_manager: ^0.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  fake_async: ^1.3.1

flutter:
  uses-material-design: true
